# Minimal Netlify Configuration - No plugins, clean build
[build]
  command = "pnpm install && pnpm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  PNPM_VERSION = "8"

# Redirects for Next.js SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
